### ISSUE TITLE
Trace Collector Not Selecting Correct Port on macOS

### ISSUE THREAD

**Issue by akash-patel** [NordicSemiconductor/pc-nrfconnect-tracecollector#27]
Tested on macOS 10.13.6
nRF Connect v3.6.1
Trace Collector v1.0.6

When connecting the DK to trace collector, with auto device/port filter enabled, it seems to select the wrong port for trace and therefore no trace data is collected. When auto device/port filter is disabled, and port # 2 for the device is selected, trace collection works fine.

Screenshots below.

![Auto_disabled_working](https://user-images.githubusercontent.com/5673084/107620666-e8224e80-6c09-11eb-93b6-a569b691f6a1.png)
![Auto_enabled_not_working](https://user-images.githubusercontent.com/5673084/107620669-e8bae500-6c09-11eb-976c-1666c08a4952.png)

**Comment by akash-patel** [comment]
I can confirm that this issue is still present with Trace Collector v1.07.

**Comment by datenreisender** [comment]
There are several different aspects to this. I will elaborate on them a bit. If you just want to know the TL&DR: We are aware of this but right now we will not do anything about it in the current Trace Collector and so I will close this ticket.

The mentioned “Auto device/port filter” tries to pick the correct port but it is not reliable in all cases. And it probably never will be possible to reliably pick the correct port automatically. 

So, our current proposal is: If you do not get a correct dump, turn off the automatic port selection and try to capture a dump on a different port.

You are working on macOS, as I can see, and sadly the automatic port selection seems to be especially unreliable on that platform.

The current Trace Collector app will be phased out in the near future, because we are working on a replacement. A preview of that replacement is already available in nRF Connect for Desktop if you are searching for “Trace Collector V2 preview” in the app list. That preview is so far still unsupported (which is why we keep the old Trace Collector around) but can already provide value to some people.

One thing where the preview can be helpful: Like the old Trace Collector it also supports creating binary traces but (unlike the old) it also supports converting some parts of the traces to a pcap file, which users can then view in Wireshark (Nordic can internally decode more parts of the trace, so if you are contacting Nordic support, it is usually better to keep ready binary traces, not just pcap files).

So by converting a binary trace to pcap with this preview, folks might be able to check whether a binary trace contains correct data and get an indicator whether a wrong port was chosen.

In the coming app we plan on also introducing a feature that automatically tells users whether the trace seems to contain parsable data (which could indicate whether a correct port is chosen), but that is not implemented yet.

So, we have plans to enhance the situation but there is nothing we are going to do about it right now.
